---
- name: 'Adicionando repositorio no ubuntu'
  apt_repository:
    repo: 'ppa:ondrej/php'
  become: yes
    
- name: 'Instalando pacotes do sistema operacional'
  apt:
    name:
    - php5
    - apache2
    - libapache2-mod-php5
    - php5-gd
    - libssh2-php
    - php5-mcrypt
    - php5-mysql
    state: latest
  become: yes