Vagrant.configure("2") do |config|
  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.box = "ubuntu/kinetic64"
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "dockerhost"
    end

    dockerhost.vm.provision "shell",
      inline: "apt-get update && apt install -y docker.io"

  end
end