---
- name: 'Efetuar o download do wordpress'
  get_url:
    url: 'https://wordpress.org/wordpress-5.1.13.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactar arquivo wordpress.tar.gz'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copia o wp-config-sample.php para wp-config.php'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    #backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_user_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: yes

- name: 'Copia do arquivo de configuração do apache de um template'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-enabled/000-default.conf'
  become: yes
  notify:
    - restart apache2

# - name: 'Copia do arquivo de configuração do apache do files'
#   copy:
#     src: 'files/000-default.conf'
#     dest: '/etc/apache2/sites-enabled/000-default.conf'
#     remote_src: no
#   become: yes
#   notify:
#     - restart apache2