Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.name = "wordpress"
  end

  config.vm.define "wordpress" do |m|
    m.vm.network "private_network", ip: "192.168.56.148"
  end

end